CREATE TABLE IF NOT EXISTS `user` (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    username VARCHAR(255) NOT NULL,
                                    nickname VARCHAR(255) NOT NULL,
                                    password VARCHAR(255) NOT NULL,
                                    created_at TIMESTAMP NOT NULL,
                                    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS post (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    user_id BIGINT NOT NULL,
                                    content VARCHAR(255) NOT NULL,
                                    created_at TIMESTAMP NOT NULL,
                                    PRIMARY KEY(id)
);

-- drop table `user`
-- drop table post
