DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE USERS
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id  VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

CREATE TABLE ARTICLE
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    author_id BIGINT       NOT NULL,
    title     VARCHAR(255) NOT NULL,
    content   TEXT         NOT NULL,
    FOREIGN KEY (author_id) REFERENCES USERS (id)
);