DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    userId   VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL
);

CREATE TABLE ARTICLE
(
    articleId VARCHAR(255) PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    content   TEXT         NOT NULL,
    imagePath VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userId    VARCHAR(255) NOT NULL,

    FOREIGN KEY (userId) REFERENCES MEMBER (userId)
);

CREATE TABLE COMMENT
(
    commentId VARCHAR(255) PRIMARY KEY,
    content   TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userId    VARCHAR(255) NOT NULL,
    articleId VARCHAR(255) NOT NULL,

    FOREIGN KEY (userId) REFERENCES MEMBER (userId),
    FOREIGN KEY (articleId) REFERENCES ARTICLE (articleId)
);