CREATE TABLE ARTICLE
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID  BIGINT,
    TITLE      VARCHAR(255),
    CONTENT    VARCHAR(255),
    IMAGE_PATH VARCHAR(255)
);

CREATE TABLE COMMENT
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    COMMENTER_ID BIGINT,
    ARTICLE_ID   BIGINT,
    CONTENT      VARCHAR(255)
);

CREATE TABLE USERS
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID    VARCHAR(255),
    PASSWORD   VARCHAR(255),
    NAME       VARCHAR(255),
    EMAIL      VARCHAR(255)
);